const DIMS=[
{id:"strategy",title:"AI Strategy & Ownership",subtitle:"Leadership mandate, ownership clarity, and strategic alignment",govTag:"Strategic Governance",
 icon:'<svg viewBox="0 0 24 24"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>',
 q:[
  {num:1,text:"Who holds formal, written accountability for AI governance in your organisation — including defined consequences when an AI system causes harm, fails, or breaches compliance?",signal:"Ownership",gap:"No named owner with a written mandate or consequence framework for AI governance failures",opt:{A:"Nobody — AI decisions happen organically with no designated owner or accountability",B:"IT or a vendor manages AI operationally, but no executive carries governance accountability or faces defined consequences",C:"A senior leader sponsors AI projects but holds no written governance mandate and faces no defined consequences for failures",D:"A named executive or dedicated role holds a written AI governance mandate, with explicit authority, defined responsibilities, and clear consequences for governance failures"}},
  {num:2,text:"Does your organisation have a board-approved AI strategy that defines permitted use cases, explicitly prohibited applications, risk appetite, and a formal review cadence?",signal:"AI Strategy",gap:"No board-approved AI strategy defining permitted uses, prohibited applications, or risk appetite",opt:{A:"No AI strategy exists — tools are adopted case by case with no overarching plan or defined boundaries",B:"Informal thinking exists but nothing has been written, board-approved, or communicated to the organisation",C:"A strategy document exists but lacks board approval, does not address prohibited applications, and has not been updated in over 12 months",D:"A board-approved AI strategy defines permitted use cases, explicitly prohibited applications, risk appetite, and is reviewed and updated at least annually"}},
  {num:3,text:"How complete and current is your organisation’s inventory of all AI systems in operation — including tools adopted by individual teams or employees without central IT approval?",signal:"AI Inventory",gap:"No complete AI system inventory — ungoverned tools operate outside organisational oversight",opt:{A:"We have no formal inventory and cannot say with confidence how many AI tools the organisation is running",B:"We track centrally procured AI tools but have no visibility into tools adopted independently by departments or individuals",C:"An inventory exists but is known to be incomplete — shadow deployments are suspected and no regular audit is in place",D:"A continuously maintained AI registry captures every system in production, is audited at least quarterly, and flags new or unapproved deployments automatically"}}
 ]
},
{id:"process",title:"Process & Deployment Controls",subtitle:"How AI is approved, deployed, monitored, and corrected in operations",govTag:"Operational Governance",
 icon:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"></rect><rect x="14" y="3" width="7" height="7" rx="1"></rect><rect x="3" y="14" width="7" height="7" rx="1"></rect><path d="M17.5 17.5L14 14"></path></svg>',
 q:[
  {num:4,text:"Is there a mandatory, enforced approval gate that every AI system must pass before going live — covering performance benchmarks, bias testing, security review, and compliance sign-off?",signal:"Deployment Gate",gap:"No mandatory pre-deployment approval gate — AI goes live without performance, bias, or compliance verification",opt:{A:"AI tools go live as soon as purchased or built — there is no formal testing or approval requirement",B:"Some informal testing occurs but there is no structured gate, no defined criteria, and adherence is inconsistent",C:"An approval checklist exists but exceptions are common, bias testing is absent, and compliance sign-off is not always obtained",D:"Every AI system undergoes a mandatory pre-deployment review with defined performance benchmarks, bias testing, security assessment, and documented compliance sign-off before going live"}},
  {num:5,text:"Once an AI system is live, how does your organisation detect when its performance, accuracy, or output quality has degraded — and what triggers corrective action?",signal:"Model Monitoring",gap:"No post-deployment AI monitoring — model drift and performance degradation go undetected",opt:{A:"We do not monitor AI systems post-deployment — problems surface only when errors become visible or users complain",B:"Monitoring is manual and ad hoc — individuals sometimes notice issues but there is no structured process or alerting",C:"Basic performance metrics are tracked for major systems, but drift thresholds, automated alerts, and retraining triggers are not formally defined",D:"All production AI systems have automated monitoring with defined drift thresholds, alerting pipelines, and documented retraining or rollback triggers"}},
  {num:6,text:"When an AI system produces harmful, biased, or materially incorrect outputs, how quickly can your organisation detect the failure, contain its impact, and restore correct operations?",signal:"Incident Response",gap:"No tested AI incident detection, containment, or rollback capability — harm escalates before it is caught",opt:{A:"We would likely not detect a problem until significant harm had already occurred — there is no detection mechanism",B:"Detection depends on manual observation or external complaint — there is no formal escalation path or defined response owner",C:"An escalation procedure exists for major incidents but rollback capability, root-cause protocols, and stakeholder communication plans have not been tested",D:"A documented, tested AI incident response plan covers detection, escalation, containment, rollback, root-cause analysis, and stakeholder communication within defined SLAs"}},
  {num:7,text:"Are AI-assisted or AI-driven decisions logged with enough detail — inputs, model version, outputs, and timestamp — to fully reconstruct any decision on demand for audit, investigation, or regulatory review?",signal:"Decision Audit Trail",gap:"AI decisions are not reconstructible — inputs, model context, and outputs are not captured for audit",opt:{A:"AI outputs are consumed directly with no logging — there is no record of what the system recommended or decided",B:"Some logs exist but record only final outputs, lacking the inputs, model version, and context needed for meaningful audit",C:"Structured logging covers most AI decisions but gaps remain across some systems and logs are not reviewed on a defined cadence",D:"All AI decisions are logged with inputs, model version, output, confidence level, and timestamp — enabling full reconstruction and meeting regulatory audit requirements within agreed timeframes"}}
 ]
},
{id:"data",title:"Data Governance & Quality",subtitle:"Lineage, access controls, privacy protections, and data fitness for AI",govTag:"Data Governance",
 icon:'<svg viewBox="0 0 24 24"><ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M21 12c0 1.66-4.03 3-9 3S3 13.66 3 12"></path><path d="M3 5v14c0 1.66 4.03 3 9 3s9-1.34 9-3V5"></path></svg>',
 q:[
  {num:8,text:"Does a documented, enforced policy explicitly define which data sources may be used to train, fine-tune, test, or operate each AI system — and which are prohibited — with legal and compliance sign-off?",signal:"Data Use Policy",gap:"No enforced AI data use policy — data flows into AI systems without permissibility controls",opt:{A:"No data governance policy exists — data flows into AI systems without restriction or documentation",B:"A general data policy exists but does not address AI-specific use cases, training data, or operational data feeds",C:"AI data use is partially addressed in policy but coverage is incomplete and enforcement relies on individual discretion",D:"A dedicated AI data use policy covers all systems, distinguishes permitted from prohibited sources per use case, is reviewed annually by legal and compliance, and is actively enforced"}},
  {num:9,text:"Can your organisation trace — for every AI system — exactly which data sources feed it, who formally authorised that use, and when that authorisation was granted or last reviewed?",signal:"Data Lineage",gap:"No data lineage or authorisation records — AI data sources are untracked and accountability is absent",opt:{A:"We have no visibility into the data sources feeding our AI systems — this information is not captured",B:"We know broadly which systems supply data to AI but no formal authorisation records or lineage documentation exists",C:"Lineage is documented for some AI systems but coverage is incomplete and authorisation records are not kept current",D:"Full data lineage and authorisation records are maintained for every AI system, reviewed at least annually, and updated whenever data sources or use cases change"}},
  {num:10,text:"What controls prevent personal, sensitive, or regulated data from entering AI systems without explicit consent verification, appropriate anonymisation, data minimisation, and role-based access controls?",signal:"PII & Privacy",gap:"Personal and sensitive data enters AI systems without consistent consent verification or anonymisation controls",opt:{A:"Personal data flows into AI systems without restriction — no consent checks, anonymisation, or access controls are applied",B:"We rely entirely on vendor privacy settings — no internal consent tracking, data minimisation, or access controls have been implemented",C:"Some PII controls exist for specific AI systems but are not systematically applied across all pipelines and gaps are known to exist",D:"All AI pipelines enforce consent verification, data minimisation, anonymisation or pseudonymisation, and role-based access — with controls audited at least annually"}},
  {num:11,text:"For AI models trained or fine-tuned on your data — or procured from a vendor — can you confirm the training data was lawfully obtained, properly consented, and fit for that AI purpose?",signal:"Training Data Provenance",gap:"Training data consent and provenance unverified — unlawful data use in AI training creates legal and regulatory exposure",opt:{A:"We cannot confirm the provenance or consent status of training data — this has never been assessed for any model we use",B:"We assume vendor-supplied models are compliant but hold no evidence, no contractual warranty, and have done no independent verification",C:"Training data provenance is documented for internally built models but vendor-supplied and foundation models have not been assessed",D:"All models — internal and vendor-supplied — are covered by documented training data provenance records, contractual consent warranties, and periodic compliance reviews"}}
 ]
},
{id:"accountability",title:"Accountability & Ethical AI",subtitle:"Bias controls, explainability, human oversight, and responsible AI standards",govTag:"Ethical Governance",
 icon:'<svg viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><polyline points="9 12 11 14 15 10"></polyline></svg>',
 q:[
  {num:12,text:"Has your organisation formally defined, approved, and published a set of ethical principles that govern how AI must — and must not — be used?",signal:"AI Ethics Policy",gap:"No approved AI ethics policy or principles",opt:{A:"No ethical guidelines exist — this has not been formally discussed at any level",B:"We rely on vendor ethics statements without maintaining any internal standards",C:"Ethics principles are in draft or informally understood, but not formally approved or enforced",D:"A published AI ethics policy governs all internal use and is enforced through mandatory training and review"}},
  {num:13,text:"How does your organisation systematically detect, measure, and remediate bias in AI outputs that affect customers, employees, or applicants?",signal:"Bias Detection",gap:"No bias testing, monitoring, or remediation process",opt:{A:"We do not test for bias — we assume that vendor-supplied models are fair",B:"Bias is only addressed reactively if a complaint or visible problem arises",C:"Bias testing occurs at initial deployment but there is no ongoing monitoring programme",D:"Structured bias audits run at deployment and on a recurring schedule, with documented remediation workflows"}},
  {num:14,text:"When an AI system makes a decision that directly affects a person — such as a customer, employee, or applicant — can that decision be explained clearly, and is there a human review or appeal mechanism?",signal:"Explainability",gap:"AI decisions cannot be explained or challenged by affected parties",opt:{A:"AI decisions are black-box outputs — no explanation is possible or offered",B:"Explanations are sometimes possible but depend entirely on the individual handling the case",C:"Explanation guidelines exist but are not consistently applied across all AI-driven decisions",D:"All AI-driven decisions include a documented plain-language explanation and a formal human review or appeal mechanism"}}
 ]
},
{id:"risk",title:"Risk, Compliance & Security",subtitle:"Regulatory compliance, vendor risk, and AI-specific threat management",govTag:"Risk Governance",
 icon:'<svg viewBox="0 0 24 24"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>',
 q:[
  {num:15,text:"Has your organisation mapped which regulations — such as GDPR, CCPA, HIPAA, or the EU AI Act — apply to each of your current and planned AI use cases?",signal:"Regulatory Map",gap:"No regulatory compliance mapping for AI systems",opt:{A:"We have not reviewed which regulations apply to our AI systems",B:"We are generally aware of relevant regulations but have not mapped them to specific AI systems",C:"Key regulations are identified for major AI systems, but smaller tools and edge cases are not covered",D:"A comprehensive regulatory compliance map covers all AI systems and is updated when regulations change"}},
  {num:16,text:"How thoroughly are third-party AI vendors and tools assessed for security vulnerabilities, compliance posture, and data handling practices before being approved for use?",signal:"Vendor Risk",gap:"No structured vendor AI risk assessment process",opt:{A:"We adopt AI vendors based on reputation or convenience — no formal assessment is conducted",B:"We review vendor terms of service but do not conduct security or compliance due diligence",C:"A standard vendor assessment is done, but it does not specifically address AI-related risks",D:"All AI vendors undergo a dedicated security, compliance, and AI-specific risk assessment before onboarding"}},
  {num:17,text:"Does your organisation have specific controls to defend against AI-targeted threats — such as prompt injection, adversarial inputs, model inversion, or data poisoning?",signal:"AI Security",gap:"No AI-specific cybersecurity controls in place",opt:{A:"We are not aware of AI-specific threats and have no controls targeting them",B:"We rely on general cybersecurity policies but have no AI-specific threat detection or controls",C:"Some AI-targeted controls exist for critical systems but coverage across all deployments is incomplete",D:"AI-specific security controls are implemented, tested regularly, and reviewed against emerging threat intelligence"}}
 ]
},
{id:"culture",title:"Culture, Talent & Change Management",subtitle:"AI literacy, human enablement, and governance adoption across the organisation",govTag:"People Governance",
 icon:'<svg viewBox="0 0 24 24"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>',
 q:[
  {num:18,text:"What proportion of employees who regularly use or are affected by AI tools have completed formal, role-specific training on responsible AI use, its limitations, and their governance obligations?",signal:"AI Literacy",gap:"Workforce lacks mandatory AI governance literacy training",opt:{A:"No formal AI training programme exists for any employees",B:"Training is ad hoc, informal, and only available to those who actively request it",C:"Training exists and is available, but completion is not tracked, required, or kept current",D:"All relevant employees complete mandatory, role-specific AI literacy training that is refreshed regularly"}},
  {num:19,text:"Is there a clear, accessible, and psychologically safe channel for employees to report AI errors, flag ethical concerns, or challenge AI-driven decisions — without fear of repercussion?",signal:"Speak-Up Channel",gap:"No safe mechanism for employees to report AI concerns or errors",opt:{A:"No formal mechanism exists — concerns must be raised informally through a manager",B:"General HR or compliance channels exist but are not designed or promoted for AI-specific concerns",C:"An AI-specific reporting channel exists but lacks broad awareness or guaranteed follow-up",D:"A well-publicised AI ethics reporting channel offers guaranteed anonymity, documented response timelines, and visible follow-through"}},
  {num:20,text:"How visibly and consistently does senior leadership model responsible AI governance behaviours — beyond signing policy documents — in ways that shape day-to-day organisational culture?",signal:"Leadership Signal",gap:"Leadership does not actively model or reinforce AI governance as a cultural priority",opt:{A:"Leadership is not visibly engaged with AI governance beyond approving tools or budgets",B:"Leadership mentions AI governance occasionally but does not hold teams accountable for it",C:"Leaders discuss governance in strategic forums but it is not embedded in performance culture or daily behaviour",D:"Leadership publicly champions responsible AI, holds teams accountable, and integrates governance into performance reviews and team rituals"}}
 ]
}
];

const TOTAL_Q=20;
const SM={A:1,B:2,C:3,D:4};
const MAT=[
  {id:"unprepared",min:1,max:1.9,label:"Ungoverned",status:"unprepared",rec:"Critical exposure. Your AI operations carry unmanaged legal, ethical, and operational risk. Three immediate actions before scaling any AI further: (1) name an executive with a written governance mandate, (2) document which data may and may not be used in AI systems, and (3) create a basic incident escalation protocol. Engage your legal and compliance teams within 30 days."},
  {id:"early",min:2,max:2.6,label:"Emerging Governance",status:"early",rec:"Foundations are forming but significant exposure remains. Your 60-day priorities: formalise AI ownership with a written accountability mandate, implement audit logging on all AI-assisted decisions, complete a regulatory mapping exercise covering GDPR and the EU AI Act, and launch mandatory AI literacy training for all AI-adjacent roles. Resolve your lowest-scoring dimension first — it carries the highest aggregate risk."},
  {id:"ready",min:2.7,max:3.3,label:"Governance Capable",status:"ready",rec:"Core governance is operational. The next stage is consistency and scale — standardise deployment gates across every AI system, embed governance KPIs into quarterly leadership reviews, and schedule recurring bias audits. A focused 90-day programme targeting your weakest dimension will advance you to Exemplary status. Begin benchmarking against ISO 42001 to identify systematic gaps."},
  {id:"mature",min:3.4,max:4,label:"Governance Exemplary",status:"mature",rec:"Your governance posture is comprehensive and mature. Sustain your lead by commissioning annual third-party audits, formally benchmarking against ISO 42001 and the EU AI Act, and establishing an AI Ethics Advisory panel. Publishing a public AI Transparency Report is your next competitive differentiator. At this level, governance excellence is a demonstrable business and regulatory advantage."}
];

function getM(a){return MAT.find(m=>a>=m.min&&a<=m.max)||MAT[0];}
