const DIMS=[
{id:"strategy",title:"AI Strategy & Ownership",subtitle:"Leadership mandate, ownership clarity, and strategic alignment",govTag:"Strategic Governance",
 icon:'<svg viewBox="0 0 24 24"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>',
 q:[
  {num:1,text:"Who holds formal, written accountability for AI governance in your organisation — including defined consequences when an AI system causes harm, fails, or breaches compliance?",signal:"Ownership",gap:"No named owner with a written mandate or consequence framework for AI governance failures",opt:{A:"Nobody — AI decisions happen organically with no designated owner or accountability",B:"IT or a vendor manages AI operationally, but no executive carries governance accountability or faces defined consequences",C:"A senior leader sponsors AI projects but holds no written governance mandate and faces no defined consequences for failures",D:"A named executive or dedicated role holds a written AI governance mandate, with explicit authority, defined responsibilities, and clear consequences for governance failures"}},
  {num:2,text:"Does your organisation have a board-approved AI strategy that defines permitted use cases, explicitly prohibited applications, risk appetite, and a formal review cadence?",signal:"AI Strategy",gap:"No board-approved AI strategy defining permitted uses, prohibited applications, or risk appetite",opt:{A:"No AI strategy exists — tools are adopted case by case with no overarching plan or defined boundaries",B:"Informal thinking exists but nothing has been written, board-approved, or communicated to the organisation",C:"A strategy document exists but lacks board approval, does not address prohibited applications, and has not been updated in over 12 months",D:"A board-approved AI strategy defines permitted use cases, explicitly prohibited applications, risk appetite, and is reviewed and updated at least annually"}},
  {num:3,text:"How complete and current is your organisation’s inventory of all AI systems in operation — including tools adopted by individual teams or employees without central IT approval?",signal:"AI Inventory",gap:"No complete AI system inventory — ungoverned tools operate outside organisational oversight",opt:{A:"We have no formal inventory and cannot say with confidence how many AI tools the organisation is running",B:"We track centrally procured AI tools but have no visibility into tools adopted independently by departments or individuals",C:"An inventory exists but is known to be incomplete — shadow deployments are suspected and no regular audit is in place",D:"A continuously maintained AI registry captures every system in production, is audited at least quarterly, and flags new or unapproved deployments automatically"}}
 ]
},
{id:"process",title:"Process & Deployment Controls",subtitle:"How AI is approved, deployed, monitored, and corrected in operations",govTag:"Operational Governance",
 icon:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"></rect><rect x="14" y="3" width="7" height="7" rx="1"></rect><rect x="3" y="14" width="7" height="7" rx="1"></rect><path d="M17.5 17.5L14 14"></path></svg>',
 q:[
  {num:4,text:"Is there a formal approval and testing gate that every AI tool or model must pass before going live in a production environment?",signal:"Deployment Gate",gap:"No pre-production AI approval or testing process",opt:{A:"AI tools go live immediately once purchased — there is no testing or review",B:"Some informal testing happens, but there is no structured approval gate",C:"A checklist exists, but adherence is inconsistent and not enforced",D:"All AI systems pass a formal review covering performance, risk, bias, and compliance before deployment"}},
  {num:5,text:"Are AI-assisted decisions in your workflows systematically logged, timestamped, and retrievable for audit or review?",signal:"Auditability",gap:"AI decisions are not logged or auditable",opt:{A:"AI outputs are used directly — no record is kept of what the AI decided or recommended",B:"Some logs exist, but they are inconsistent, unstructured, and not built for audit",C:"Logs are maintained for most AI-assisted decisions but are not reviewed on a cadence",D:"All AI decisions are logged, timestamped, and reviewed through a structured audit programme"}},
  {num:6,text:"When an AI system produces a harmful or incorrect output, how quickly can your organisation detect it, contain it, and restore the correct process?",signal:"Incident Response",gap:"No AI-specific incident detection or rollback capability",opt:{A:"We would likely not know until significant harm had already occurred",B:"Detection depends on manual observation — there is no formal escalation path",C:"We have informal escalation procedures but no tested rollback or containment protocol",D:"A documented AI incident response plan with tested rollback and root-cause procedures is in place"}},
  {num:7,text:"Before AI is applied to a business process, how thoroughly are the affected workflows documented, optimised, and baselined?",signal:"Process Clarity",gap:"Processes inadequately mapped before AI is applied",opt:{A:"Processes are largely undocumented — we automate whatever exists as-is",B:"Key steps are known informally, but not formally mapped or optimised first",C:"Most AI-targeted processes are documented but not routinely updated after deployment",D:"All AI-targeted processes are fully mapped, optimised, and performance-baselined before AI is applied"}}
 ]
},
{id:"data",title:"Data Governance & Quality",subtitle:"Lineage, access controls, privacy protections, and data fitness for AI",govTag:"Data Governance",
 icon:'<svg viewBox="0 0 24 24"><ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M21 12c0 1.66-4.03 3-9 3S3 13.66 3 12"></path><path d="M3 5v14c0 1.66 4.03 3 9 3s9-1.34 9-3V5"></path></svg>',
 q:[
  {num:8,text:"Does a documented data governance policy exist that explicitly defines which data may and may not be used to train, test, or operate AI systems?",signal:"Data Policy",gap:"No AI-specific data use or permissibility policy",opt:{A:"No data governance policy exists for any purpose",B:"A general data policy exists but it does not address AI use cases at all",C:"AI data use is partially addressed in policy but not consistently enforced",D:"A dedicated AI data policy is maintained, reviewed by legal and compliance, and actively enforced"}},
  {num:9,text:"Can you trace exactly which data sources feed each of your AI models or tools, who authorised that use, and when?",signal:"Data Lineage",gap:"No data lineage or provenance tracking for AI inputs",opt:{A:"We have no meaningful visibility into the data sources our AI tools actually use",B:"We know broadly which systems feed AI, but there is no formal tracking or authorisation record",C:"Data lineage is documented for some AI systems but not comprehensively across all deployments",D:"Full data lineage and authorisation records are maintained for all AI systems and reviewed regularly"}},
  {num:10,text:"How does your organisation protect personal, sensitive, or regulated data when it flows through AI workflows or is used in AI training?",signal:"PII & Privacy",gap:"No PII or sensitive data protection controls in AI pipelines",opt:{A:"Personal data enters AI systems with no specific controls, consent checks, or restrictions",B:"We rely on vendor privacy settings but have built no internal controls or oversight",C:"Some PII controls exist (e.g. anonymisation) but they are not systematic across all AI pipelines",D:"All AI pipelines enforce PII anonymisation, consent tracking, data minimisation, and role-based access controls"}},
  {num:11,text:"How is the accuracy, completeness, and freshness of data feeding your AI systems validated — and how often?",signal:"Data Quality",gap:"No systematic data quality validation for AI inputs",opt:{A:"Data quality is never formally validated — we assume the data is accurate",B:"Quality is checked occasionally when errors surface, not proactively",C:"Regular validation exists for some data pipelines but is not applied across all AI inputs",D:"Automated data quality checks run continuously across all AI-feeding pipelines with documented thresholds"}}
 ]
},
{id:"accountability",title:"Accountability & Ethical AI",subtitle:"Bias controls, explainability, human oversight, and responsible AI standards",govTag:"Ethical Governance",
 icon:'<svg viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><polyline points="9 12 11 14 15 10"></polyline></svg>',
 q:[
  {num:12,text:"Has your organisation formally defined, approved, and published a set of ethical principles that govern how AI must — and must not — be used?",signal:"AI Ethics Policy",gap:"No approved AI ethics policy or principles",opt:{A:"No ethical guidelines exist — this has not been formally discussed at any level",B:"We rely on vendor ethics statements without maintaining any internal standards",C:"Ethics principles are in draft or informally understood, but not formally approved or enforced",D:"A published AI ethics policy governs all internal use and is enforced through mandatory training and review"}},
  {num:13,text:"How does your organisation systematically detect, measure, and remediate bias in AI outputs that affect customers, employees, or applicants?",signal:"Bias Detection",gap:"No bias testing, monitoring, or remediation process",opt:{A:"We do not test for bias — we assume that vendor-supplied models are fair",B:"Bias is only addressed reactively if a complaint or visible problem arises",C:"Bias testing occurs at initial deployment but there is no ongoing monitoring programme",D:"Structured bias audits run at deployment and on a recurring schedule, with documented remediation workflows"}},
  {num:14,text:"When an AI system makes a decision that directly affects a person — such as a customer, employee, or applicant — can that decision be explained clearly, and is there a human review or appeal mechanism?",signal:"Explainability",gap:"AI decisions cannot be explained or challenged by affected parties",opt:{A:"AI decisions are black-box outputs — no explanation is possible or offered",B:"Explanations are sometimes possible but depend entirely on the individual handling the case",C:"Explanation guidelines exist but are not consistently applied across all AI-driven decisions",D:"All AI-driven decisions include a documented plain-language explanation and a formal human review or appeal mechanism"}}
 ]
},
{id:"risk",title:"Risk, Compliance & Security",subtitle:"Regulatory compliance, vendor risk, and AI-specific threat management",govTag:"Risk Governance",
 icon:'<svg viewBox="0 0 24 24"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>',
 q:[
  {num:15,text:"Has your organisation mapped which regulations — such as GDPR, CCPA, HIPAA, or the EU AI Act — apply to each of your current and planned AI use cases?",signal:"Regulatory Map",gap:"No regulatory compliance mapping for AI systems",opt:{A:"We have not reviewed which regulations apply to our AI systems",B:"We are generally aware of relevant regulations but have not mapped them to specific AI systems",C:"Key regulations are identified for major AI systems, but smaller tools and edge cases are not covered",D:"A comprehensive regulatory compliance map covers all AI systems and is updated when regulations change"}},
  {num:16,text:"How thoroughly are third-party AI vendors and tools assessed for security vulnerabilities, compliance posture, and data handling practices before being approved for use?",signal:"Vendor Risk",gap:"No structured vendor AI risk assessment process",opt:{A:"We adopt AI vendors based on reputation or convenience — no formal assessment is conducted",B:"We review vendor terms of service but do not conduct security or compliance due diligence",C:"A standard vendor assessment is done, but it does not specifically address AI-related risks",D:"All AI vendors undergo a dedicated security, compliance, and AI-specific risk assessment before onboarding"}},
  {num:17,text:"Does your organisation have specific controls to defend against AI-targeted threats — such as prompt injection, adversarial inputs, model inversion, or data poisoning?",signal:"AI Security",gap:"No AI-specific cybersecurity controls in place",opt:{A:"We are not aware of AI-specific threats and have no controls targeting them",B:"We rely on general cybersecurity policies but have no AI-specific threat detection or controls",C:"Some AI-targeted controls exist for critical systems but coverage across all deployments is incomplete",D:"AI-specific security controls are implemented, tested regularly, and reviewed against emerging threat intelligence"}}
 ]
},
{id:"culture",title:"Culture, Talent & Change Management",subtitle:"AI literacy, human enablement, and governance adoption across the organisation",govTag:"People Governance",
 icon:'<svg viewBox="0 0 24 24"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>',
 q:[
  {num:18,text:"What proportion of employees who regularly use or are affected by AI tools have completed formal, role-specific training on responsible AI use, its limitations, and their governance obligations?",signal:"AI Literacy",gap:"Workforce lacks mandatory AI governance literacy training",opt:{A:"No formal AI training programme exists for any employees",B:"Training is ad hoc, informal, and only available to those who actively request it",C:"Training exists and is available, but completion is not tracked, required, or kept current",D:"All relevant employees complete mandatory, role-specific AI literacy training that is refreshed regularly"}},
  {num:19,text:"Is there a clear, accessible, and psychologically safe channel for employees to report AI errors, flag ethical concerns, or challenge AI-driven decisions — without fear of repercussion?",signal:"Speak-Up Channel",gap:"No safe mechanism for employees to report AI concerns or errors",opt:{A:"No formal mechanism exists — concerns must be raised informally through a manager",B:"General HR or compliance channels exist but are not designed or promoted for AI-specific concerns",C:"An AI-specific reporting channel exists but lacks broad awareness or guaranteed follow-up",D:"A well-publicised AI ethics reporting channel offers guaranteed anonymity, documented response timelines, and visible follow-through"}},
  {num:20,text:"How visibly and consistently does senior leadership model responsible AI governance behaviours — beyond signing policy documents — in ways that shape day-to-day organisational culture?",signal:"Leadership Signal",gap:"Leadership does not actively model or reinforce AI governance as a cultural priority",opt:{A:"Leadership is not visibly engaged with AI governance beyond approving tools or budgets",B:"Leadership mentions AI governance occasionally but does not hold teams accountable for it",C:"Leaders discuss governance in strategic forums but it is not embedded in performance culture or daily behaviour",D:"Leadership publicly champions responsible AI, holds teams accountable, and integrates governance into performance reviews and team rituals"}}
 ]
}
];

const TOTAL_Q=20;
const SM={A:1,B:2,C:3,D:4};
const MAT=[
  {id:"unprepared",min:1,max:1.9,label:"Ungoverned",status:"unprepared",rec:"Critical exposure. Your AI operations carry unmanaged legal, ethical, and operational risk. Three immediate actions before scaling any AI further: (1) name an executive with a written governance mandate, (2) document which data may and may not be used in AI systems, and (3) create a basic incident escalation protocol. Engage your legal and compliance teams within 30 days."},
  {id:"early",min:2,max:2.6,label:"Emerging Governance",status:"early",rec:"Foundations are forming but significant exposure remains. Your 60-day priorities: formalise AI ownership with a written accountability mandate, implement audit logging on all AI-assisted decisions, complete a regulatory mapping exercise covering GDPR and the EU AI Act, and launch mandatory AI literacy training for all AI-adjacent roles. Resolve your lowest-scoring dimension first — it carries the highest aggregate risk."},
  {id:"ready",min:2.7,max:3.3,label:"Governance Capable",status:"ready",rec:"Core governance is operational. The next stage is consistency and scale — standardise deployment gates across every AI system, embed governance KPIs into quarterly leadership reviews, and schedule recurring bias audits. A focused 90-day programme targeting your weakest dimension will advance you to Exemplary status. Begin benchmarking against ISO 42001 to identify systematic gaps."},
  {id:"mature",min:3.4,max:4,label:"Governance Exemplary",status:"mature",rec:"Your governance posture is comprehensive and mature. Sustain your lead by commissioning annual third-party audits, formally benchmarking against ISO 42001 and the EU AI Act, and establishing an AI Ethics Advisory panel. Publishing a public AI Transparency Report is your next competitive differentiator. At this level, governance excellence is a demonstrable business and regulatory advantage."}
];

function getM(a){return MAT.find(m=>a>=m.min&&a<=m.max)||MAT[0];}
